### Create ToDO
POST http://localhost:8000/todo
Content-Type: application/json

{
    "name":"",
    "description":"",
    "state":false
}

### Get ToDos
GET http://localhost:8000/todo

### Get ToDo
GET http://localhost:8000/todo/<id>

### Update ToDos
PUT http://localhost:8000/todo/<id>
Content-Type: application/json

{
    "name":"",
    "description":"",
    "state":false
}
### Delete ToDo
DELETE http://localhost:8000/todo/<id>